language: rust
rust:
  - stable

os:
  - linux
  - osx
  - windows

jobs:
  fast_finish: true

notifications:
  email:
    on_failure: change
    on_success: change

branches:
  only:
    - main

# cache: cargo
